name: Generate Podcast Feeds
on: [push]
jobs:
  build:
    runs-on: python-3.13.0b1-alpine3.20
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Run Feed Generator
        uses: daemosity/podcast-generator@main # until a release is created, can reference a specific branch
